/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLlmStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/city": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIncident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{approval_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChunk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setSimulationSpeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/inject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["injectScenarioEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        LlmStatus: {
            /** @enum {string} */
            provider: "anthropic" | "mock" | "none";
            model: string | null;
        };
        XY: {
            x: number;
            y: number;
        };
        ViewBox: {
            x: number;
            y: number;
            width: number;
            height: number;
        };
        /** @enum {string} */
        Band: "normal" | "watch" | "warning" | "critical";
        /** @enum {string} */
        Hazard: "landslide" | "flood";
        ZoneState: {
            saturation: number;
            rain_24h_mm: number;
            rain_intensity_mm_h: number;
            landslide_index: number;
            flood_index: number;
            band: components["schemas"]["Band"];
            updated_sim_time: string;
        };
        Zone: {
            id: string;
            name: string;
            slope_deg: number;
            soil_type: string;
            population: number;
            drains_to_channel_id?: string | null;
            svg_path: string;
            label_xy: components["schemas"]["XY"];
            state: components["schemas"]["ZoneState"];
        };
        Road: {
            id: string;
            name: string;
            zone_ids: string[];
            /** @enum {string} */
            status: "open" | "closed";
            is_evacuation_route: boolean;
            is_bridge: boolean;
            svg_path: string;
        };
        Channel: {
            id: string;
            name: string;
            design_capacity_m3s: number;
            current_capacity_m3s: number;
            blocked_fraction: number;
            downstream_zone_id?: string | null;
            svg_path: string;
        };
        Project: {
            id: string;
            name: string;
            zone_id: string;
            /** @enum {string} */
            status: "active" | "halted";
            excavation_depth_m: number;
            planned_depth_m: number;
            permit_doc_id: string | null;
            xy: components["schemas"]["XY"];
        };
        Sensor: {
            id: string;
            /** @enum {string} */
            kind: "rain" | "soil" | "channel";
            zone_id: string;
            unit: string;
            xy: components["schemas"]["XY"];
            last_value?: number | null;
            last_sim_time?: string | null;
        };
        Crew: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "available" | "dispatched" | "en_route" | "on_site" | "blocked";
            location_zone_id: string;
            target_zone_id?: string | null;
            task?: string | null;
            xy: components["schemas"]["XY"];
        };
        Shelter: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "open" | "closed";
            capacity: number;
            occupancy: number;
            zone_id: string;
            xy: components["schemas"]["XY"];
        };
        PumpUnit: {
            id: string;
            /** @enum {string} */
            status: "at_depot" | "deployed";
            channel_id?: string | null;
        };
        PumpDepot: {
            zone_id: string;
            xy: components["schemas"]["XY"];
            units: components["schemas"]["PumpUnit"][];
        };
        Hospital: {
            id: string;
            name: string;
            zone_id: string;
            beds: number;
            xy: components["schemas"]["XY"];
        };
        MapFeature: {
            id: string;
            /** @enum {string} */
            kind: "river" | "hill_contour" | "lake" | "label";
            svg_path: string;
            label?: string | null;
        };
        BandThresholds: {
            watch: number;
            warning: number;
            critical: number;
        };
        Bands: {
            landslide: components["schemas"]["BandThresholds"];
            flood: components["schemas"]["BandThresholds"];
        };
        Injection: {
            id: string;
            label: string;
        };
        Scenario: {
            id: string;
            name: string;
            injections: components["schemas"]["Injection"][];
        };
        City: {
            view_box: components["schemas"]["ViewBox"];
            zones: components["schemas"]["Zone"][];
            roads: components["schemas"]["Road"][];
            channels: components["schemas"]["Channel"][];
            projects: components["schemas"]["Project"][];
            sensors: components["schemas"]["Sensor"][];
            crews: components["schemas"]["Crew"][];
            shelters: components["schemas"]["Shelter"][];
            pump_depot: components["schemas"]["PumpDepot"];
            hospitals: components["schemas"]["Hospital"][];
            map_features: components["schemas"]["MapFeature"][];
            bands: components["schemas"]["Bands"];
            scenarios: components["schemas"]["Scenario"][];
        };
        Citation: {
            id: string;
            /** @enum {string} */
            kind: "chunk" | "sensor" | "state" | "event";
            label: string;
        };
        Claim: {
            text: string;
            citation_ids: string[];
        };
        ContributingFactor: {
            factor: string;
            value: string;
            citation_ids: string[];
        };
        CitySnapshotReadings: {
            rain_intensity_mm_h: number;
            rain_24h_mm: number;
            saturation: number;
            landslide_index: number;
            flood_index: number;
            band: components["schemas"]["Band"];
        };
        SnapshotProject: {
            id: string;
            name: string;
            status: string;
            excavation_depth_m: number;
            planned_depth_m: number;
        };
        SnapshotChannel: {
            id: string;
            name: string;
            current_capacity_m3s: number;
            design_capacity_m3s: number;
            blocked_fraction: number;
        };
        SnapshotCrew: {
            id: string;
            name: string;
            status: string;
            location_zone_id: string;
        };
        CitySnapshot: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "observe";
            zone_id: string;
            sim_time: string;
            readings: components["schemas"]["CitySnapshotReadings"];
            project?: components["schemas"]["SnapshotProject"] | null;
            channel?: components["schemas"]["SnapshotChannel"] | null;
            crews: components["schemas"]["SnapshotCrew"][];
            open_roads: string[];
            closed_roads: string[];
            downstream_zone_ids: string[];
        };
        RetrievedChunk: {
            id: string;
            doc_id: string;
            doc_title: string;
            section: string;
            kind: string;
            score: number;
        };
        RetrievedChunks: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "retrieve";
            chunks: components["schemas"]["RetrievedChunk"][];
        };
        ThreatAssessment: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "assess";
            hazard: components["schemas"]["Hazard"];
            summary: string;
            contributing_factors: components["schemas"]["ContributingFactor"][];
            confidence: number;
            claims: components["schemas"]["Claim"][];
        };
        RiskPrediction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "predict";
            /** @enum {string} */
            probability_band: "low" | "moderate" | "high" | "very_high";
            time_horizon: string;
            onset_sim_time?: string | null;
            what_would_change_it: string[];
            claims: components["schemas"]["Claim"][];
        };
        CascadeLink: {
            cause: string;
            effect: string;
            affected_asset_ids: string[];
            citation_ids: string[];
        };
        CascadeAnalysis: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "cascade";
            chain: components["schemas"]["CascadeLink"][];
            affected_zone_ids: string[];
            claims: components["schemas"]["Claim"][];
        };
        ProposedAction: {
            action_id: string;
            tool: string;
            input: {
                [key: string]: unknown;
            };
            rationale: string;
            expected_effect: string;
            citation_ids: string[];
            requires_approval: boolean;
        };
        ActionPlan: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "recommend";
            actions: components["schemas"]["ProposedAction"][];
        };
        ApprovalGateResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "approval_gate";
            approval_id?: string | null;
            auto_approved_action_ids: string[];
            pending_action_ids: string[];
        };
        ExecuteResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "execute";
            action_ids: string[];
        };
        PerActionVerification: {
            action_id: string;
            /** @enum {string} */
            status: "verified" | "partially_verified" | "failed" | "pending";
            expected: string;
            observed: string;
            failures: string[];
        };
        VerificationResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "verify";
            /** @enum {string} */
            status: "verified" | "partially_verified" | "failed";
            per_action: components["schemas"]["PerActionVerification"][];
        };
        ReplanResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "replan";
            reason: string;
        };
        StepOutput: components["schemas"]["CitySnapshot"] | components["schemas"]["RetrievedChunks"] | components["schemas"]["ThreatAssessment"] | components["schemas"]["RiskPrediction"] | components["schemas"]["CascadeAnalysis"] | components["schemas"]["ActionPlan"] | components["schemas"]["ApprovalGateResult"] | components["schemas"]["ExecuteResult"] | components["schemas"]["VerificationResult"] | components["schemas"]["ReplanResult"];
        /** @enum {string} */
        NodeName: "observe" | "retrieve" | "assess" | "predict" | "cascade" | "recommend" | "approval_gate" | "execute" | "verify" | "replan";
        AgentStep: {
            id: string;
            run_id: string;
            node: components["schemas"]["NodeName"];
            /** @enum {string} */
            status: "running" | "finished" | "ungrounded" | "failed";
            started_at: string;
            finished_at?: string | null;
            duration_ms?: number | null;
            output: components["schemas"]["StepOutput"] | null;
            citations: components["schemas"]["Citation"][];
        };
        AgentRun: {
            id: string;
            incident_id: string;
            thread_id: string;
            trigger: string;
            replan_reason?: string | null;
            /** @enum {string} */
            status: "running" | "waiting_approval" | "finished" | "failed";
            started_at: string;
            finished_at?: string | null;
            steps: components["schemas"]["AgentStep"][];
        };
        /** @enum {string} */
        ApprovalStatus: "pending" | "approved" | "rejected" | "partial";
        Approval: {
            id: string;
            run_id: string;
            incident_id: string;
            proposed_actions: components["schemas"]["ProposedAction"][];
            status: components["schemas"]["ApprovalStatus"];
            requested_at: string;
            decided_at?: string | null;
            decided_by?: string | null;
            note?: string | null;
            approved_action_ids: string[];
            synthetic: boolean;
        };
        ApprovalDecision: {
            /** @enum {string} */
            decision: "approve" | "reject" | "partial";
            approved_action_ids: string[];
            note?: string | null;
        };
        StateChange: {
            /** @enum {string} */
            entity_type: "crew" | "shelter" | "road" | "project" | "channel" | "pump_unit" | "alert";
            entity_id: string;
            entity_name: string;
            field: string;
            from: string;
            to: string;
        };
        ActionVerification: {
            /** @enum {string} */
            status: "verified" | "partially_verified" | "failed" | "pending";
            expected: string;
            observed: string;
            failures: string[];
            checked_sim_time?: string | null;
        };
        /** @enum {string} */
        ActionStatus: "pending" | "executing" | "executed" | "failed";
        Action: {
            id: string;
            run_id: string;
            incident_id: string;
            tool: string;
            input: {
                [key: string]: unknown;
            };
            status: components["schemas"]["ActionStatus"];
            executed_at?: string | null;
            executed_sim_time?: string | null;
            state_changes: components["schemas"]["StateChange"][];
            verification?: components["schemas"]["ActionVerification"] | null;
        };
        Alert: {
            id: string;
            zone_id: string;
            /** @enum {string} */
            level: "advisory" | "warning" | "evacuate";
            message: string;
            issued_at: string;
            issued_sim_time: string;
        };
        /** @enum {string} */
        IncidentStatus: "open" | "closed";
        IncidentSummary: {
            id: string;
            zone_id: string;
            hazard: components["schemas"]["Hazard"];
            band: components["schemas"]["Band"];
            status: components["schemas"]["IncidentStatus"];
            opened_at: string;
            opened_sim_time: string;
            closed_at?: string | null;
            run_count: number;
            pending_approval_count: number;
        };
        Incident: {
            id: string;
            zone_id: string;
            hazard: components["schemas"]["Hazard"];
            band: components["schemas"]["Band"];
            status: components["schemas"]["IncidentStatus"];
            opened_at: string;
            opened_sim_time: string;
            closed_at?: string | null;
            runs: components["schemas"]["AgentRun"][];
            approvals: components["schemas"]["Approval"][];
            actions: components["schemas"]["Action"][];
        };
        Chunk: {
            id: string;
            doc_id: string;
            doc_title: string;
            section: string;
            kind: string;
            text: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        DocumentSection: {
            id: string;
            heading: string;
            text: string;
        };
        Document: {
            id: string;
            title: string;
            kind: string;
            sections: components["schemas"]["DocumentSection"][];
        };
        SimStatus: {
            scenario: string | null;
            running: boolean;
            speed: number;
            sim_time: string | null;
            tick: number;
        };
        SimulationStart: {
            scenario: string;
            speed: number;
            seed?: number;
        };
        SimulationSpeed: {
            speed: number;
        };
        InjectEvent: {
            id: string;
        };
        StateSnapshot: {
            city: components["schemas"]["City"];
            sim: components["schemas"]["SimStatus"];
            llm: components["schemas"]["LlmStatus"];
            incidents: components["schemas"]["Incident"][];
            approvals: components["schemas"]["Approval"][];
            actions: components["schemas"]["Action"][];
            alerts: components["schemas"]["Alert"][];
        };
        /** @enum {string} */
        EventType: "state.snapshot" | "sim.tick" | "sensor.reading" | "zone.state" | "threat.detected" | "threat.escalated" | "incident.opened" | "incident.closed" | "agent.run.started" | "agent.run.finished" | "agent.node.started" | "agent.node.finished" | "approval.requested" | "approval.decided" | "action.executed" | "action.verified" | "replan.triggered" | "alert.issued" | "scenario.event";
        EventBase: {
            id: string;
            ts: string;
            sim_time: string | null;
            incident_id?: string | null;
        };
        SimTickPayload: {
            sim_time: string;
            tick: number;
            running: boolean;
            speed: number;
        };
        SensorReadingPayload: {
            sensor_id: string;
            /** @enum {string} */
            kind: "rain" | "soil" | "channel";
            zone_id: string;
            value: number;
            unit: string;
        };
        ZoneStatePayload: components["schemas"]["ZoneState"] & {
            zone_id: string;
            prev_band?: components["schemas"]["Band"] | null;
        };
        ThreatPayload: {
            incident_id: string;
            zone_id: string;
            hazard: components["schemas"]["Hazard"];
            band: components["schemas"]["Band"];
            prev_band?: components["schemas"]["Band"] | null;
            index: number;
        };
        NodeStartedPayload: {
            run_id: string;
            incident_id: string;
            node: components["schemas"]["NodeName"];
            step_id: string;
        };
        ActionVerifiedPayload: {
            action_id: string;
            verification: components["schemas"]["ActionVerification"];
        };
        ReplanPayload: {
            incident_id: string;
            run_id: string;
            reason: string;
        };
        ScenarioEventPayload: {
            name: string;
            description: string;
        };
        StateSnapshotEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "state.snapshot";
            payload: components["schemas"]["StateSnapshot"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "state.snapshot";
        };
        SimTickEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "sim.tick";
            payload: components["schemas"]["SimTickPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sim.tick";
        };
        SensorReadingEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "sensor.reading";
            payload: components["schemas"]["SensorReadingPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sensor.reading";
        };
        ZoneStateEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "zone.state";
            payload: components["schemas"]["ZoneStatePayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "zone.state";
        };
        ThreatDetectedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "threat.detected";
            payload: components["schemas"]["ThreatPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "threat.detected";
        };
        ThreatEscalatedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "threat.escalated";
            payload: components["schemas"]["ThreatPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "threat.escalated";
        };
        IncidentOpenedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "incident.opened";
            payload: components["schemas"]["Incident"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "incident.opened";
        };
        IncidentClosedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "incident.closed";
            payload: components["schemas"]["Incident"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "incident.closed";
        };
        AgentRunStartedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "agent.run.started";
            payload: components["schemas"]["AgentRun"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent.run.started";
        };
        AgentRunFinishedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "agent.run.finished";
            payload: components["schemas"]["AgentRun"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent.run.finished";
        };
        AgentNodeStartedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "agent.node.started";
            payload: components["schemas"]["NodeStartedPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent.node.started";
        };
        AgentNodeFinishedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "agent.node.finished";
            payload: components["schemas"]["AgentStep"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "agent.node.finished";
        };
        ApprovalRequestedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "approval.requested";
            payload: components["schemas"]["Approval"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "approval.requested";
        };
        ApprovalDecidedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "approval.decided";
            payload: components["schemas"]["Approval"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "approval.decided";
        };
        ActionExecutedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "action.executed";
            payload: components["schemas"]["Action"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "action.executed";
        };
        ActionVerifiedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "action.verified";
            payload: components["schemas"]["ActionVerifiedPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "action.verified";
        };
        ReplanTriggeredEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "replan.triggered";
            payload: components["schemas"]["ReplanPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "replan.triggered";
        };
        AlertIssuedEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "alert.issued";
            payload: components["schemas"]["Alert"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "alert.issued";
        };
        ScenarioEvent: components["schemas"]["EventBase"] & {
            /** @enum {string} */
            type: "scenario.event";
            payload: components["schemas"]["ScenarioEventPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "scenario.event";
        };
        Event: components["schemas"]["StateSnapshotEvent"] | components["schemas"]["SimTickEvent"] | components["schemas"]["SensorReadingEvent"] | components["schemas"]["ZoneStateEvent"] | components["schemas"]["ThreatDetectedEvent"] | components["schemas"]["ThreatEscalatedEvent"] | components["schemas"]["IncidentOpenedEvent"] | components["schemas"]["IncidentClosedEvent"] | components["schemas"]["AgentRunStartedEvent"] | components["schemas"]["AgentRunFinishedEvent"] | components["schemas"]["AgentNodeStartedEvent"] | components["schemas"]["AgentNodeFinishedEvent"] | components["schemas"]["ApprovalRequestedEvent"] | components["schemas"]["ApprovalDecidedEvent"] | components["schemas"]["ActionExecutedEvent"] | components["schemas"]["ActionVerifiedEvent"] | components["schemas"]["ReplanTriggeredEvent"] | components["schemas"]["AlertIssuedEvent"] | components["schemas"]["ScenarioEvent"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getLlmStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmStatus"];
                };
            };
        };
    };
    getCity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["City"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                since?: string;
                type?: components["schemas"]["EventType"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    listIncidents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSummary"][];
                };
            };
        };
    };
    getIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Incident"];
                };
            };
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApprovalStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"][];
                };
            };
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
        };
    };
    listActions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Action"][];
                };
            };
        };
    };
    getAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Action"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    getChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chunk"];
                };
            };
        };
    };
    startSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationStart"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimStatus"];
                };
            };
        };
    };
    pauseSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimStatus"];
                };
            };
        };
    };
    resumeSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimStatus"];
                };
            };
        };
    };
    resetSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimStatus"];
                };
            };
        };
    };
    setSimulationSpeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationSpeed"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimStatus"];
                };
            };
        };
    };
    injectScenarioEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectEvent"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimStatus"];
                };
            };
        };
    };
}
