/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// GENERATED by scripts/gen-api.mjs from openapi.json (backend) + openapi.pending.yaml (pending overlay).
// Do not edit. Run `npm run gen:api` after a backend contract change.

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/city": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get City
         * @description Static geometry and attributes of every simulated asset, the scenarios and the inject presets.
         */
        get: operations["get_city_api_city_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chunk */
        get: operations["get_chunk_api_chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_simulation_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_simulation_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["get_snapshot_api_simulation_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Scenario */
        post: operations["select_scenario_api_simulation_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_simulation_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_api_simulation_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_simulation_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset */
        post: operations["reset_api_simulation_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance */
        post: operations["advance_api_simulation_advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Speed */
        post: operations["set_speed_api_simulation_speed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/inject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject
         * @description Apply an operator event now; returns it plus any derived events (all published on the bus).
         */
        post: operations["inject_api_simulation_inject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLlmStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detector/bands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetectorBands"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIncident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{approval_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvanceRequest */
        AdvanceRequest: {
            /**
             * Ticks
             * @default 1
             */
            ticks: number;
        };
        /** AdvanceResponse */
        AdvanceResponse: {
            /** Events Emitted */
            events_emitted: number;
            status: components["schemas"]["SimulationStatus"];
        };
        /** AmbulanceState */
        AmbulanceState: {
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "dispatched" | "maintenance";
            /** Location Zone Id */
            location_zone_id: string;
        };
        /** AmbulanceStatus */
        AmbulanceStatus: {
            /** Ambulance Id */
            ambulance_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "dispatched" | "maintenance";
            /** Location Zone Id */
            location_zone_id: string;
            /**
             * Hospital Id
             * @default
             */
            hospital_id: string;
            /**
             * Available Count
             * @default 0
             */
            available_count: number;
            /**
             * Total Count
             * @default 0
             */
            total_count: number;
        };
        /** AmbulanceStatusEvent */
        AmbulanceStatusEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "emergency.ambulance";
            payload: components["schemas"]["AmbulanceStatus"];
        };
        /** BridgeState */
        BridgeState: {
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "restricted" | "closed";
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** BridgeStatus */
        BridgeStatus: {
            /** Bridge Id */
            bridge_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "restricted" | "closed";
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** BridgeStatusEvent */
        BridgeStatusEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "infrastructure.bridge";
            payload: components["schemas"]["BridgeStatus"];
        };
        /** ChannelState */
        ChannelState: {
            /** Blocked Fraction */
            blocked_fraction: number;
            /** Capacity M3S */
            capacity_m3s: number;
            /**
             * Extra Capacity M3S
             * @default 0
             */
            extra_capacity_m3s: number;
            /**
             * Gate Closed
             * @default false
             */
            gate_closed: boolean;
            /**
             * Flow M3S
             * @default 0
             */
            flow_m3s: number;
            /**
             * Overflow M3S
             * @default 0
             */
            overflow_m3s: number;
        };
        /** CityMap */
        CityMap: {
            /** Name */
            name: string;
            view_box: components["schemas"]["ViewBox"];
            /** Zones */
            zones: components["schemas"]["MapZone"][];
            /** Roads */
            roads: components["schemas"]["MapRoad"][];
            /** Bridges */
            bridges: components["schemas"]["MapBridge"][];
            /** Channels */
            channels: components["schemas"]["MapChannel"][];
            /** Slopes */
            slopes: components["schemas"]["MapSlope"][];
            /** Projects */
            projects: components["schemas"]["MapProject"][];
            /** Sensors */
            sensors: components["schemas"]["MapSensor"][];
            /** Crews */
            crews: components["schemas"]["MapCrew"][];
            /** Shelters */
            shelters: components["schemas"]["MapShelter"][];
            /** Hospitals */
            hospitals: components["schemas"]["MapHospital"][];
            pump_depot: components["schemas"]["PumpDepot"];
            /** Map Features */
            map_features: components["schemas"]["MapFeature"][];
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioInfo"][];
            /** Injections */
            injections: components["schemas"]["InjectionPreset"][];
        };
        /** ConstructionActivity */
        ConstructionActivity: {
            /** Project Id */
            project_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "halted";
            /**
             * Activity
             * @enum {string}
             */
            activity: "excavating" | "idle" | "halted";
            /** Excavation Depth M */
            excavation_depth_m: number;
            /**
             * Planned Depth M
             * @default 0
             */
            planned_depth_m: number;
        };
        /** ConstructionActivityEvent */
        ConstructionActivityEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "infrastructure.construction";
            payload: components["schemas"]["ConstructionActivity"];
        };
        /** CrewState */
        CrewState: {
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "dispatched" | "en_route" | "on_site" | "blocked" | "busy" | "off_duty";
            /** Location Zone Id */
            location_zone_id: string;
            /**
             * Task
             * @default
             */
            task: string;
        };
        /** DrainageObservation */
        DrainageObservation: {
            /** Gauge Id */
            gauge_id: string;
            /** Channel Id */
            channel_id: string;
            /** Flow M3S */
            flow_m3s: number;
            /** Capacity M3S */
            capacity_m3s: number;
            /** Load Ratio */
            load_ratio: number;
            /** Blocked Fraction */
            blocked_fraction: number;
            /** Overflow M3S */
            overflow_m3s: number;
        };
        /** DrainageObservationEvent */
        DrainageObservationEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "environment.drainage";
            payload: components["schemas"]["DrainageObservation"];
        };
        /** DrainageObstruction */
        DrainageObstruction: {
            /** Channel Id */
            channel_id: string;
            /** Blocked Fraction */
            blocked_fraction: number;
            /**
             * Cause
             * @default
             */
            cause: string;
        };
        /** DrainageObstructionEvent */
        DrainageObstructionEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "infrastructure.drainage_obstruction";
            payload: components["schemas"]["DrainageObstruction"];
        };
        /**
         * Event
         * @description Any event on the bus or the WebSocket, discriminated by ``event_type``.
         */
        Event: components["schemas"]["SimTickEvent"] | components["schemas"]["SimStatusEvent"] | components["schemas"]["SimSnapshotEvent"] | components["schemas"]["HeartbeatEvent"] | components["schemas"]["ScenarioStageEvent"] | components["schemas"]["WeatherObservationEvent"] | components["schemas"]["WeatherForecastEvent"] | components["schemas"]["SoilObservationEvent"] | components["schemas"]["RiverObservationEvent"] | components["schemas"]["DrainageObservationEvent"] | components["schemas"]["SlopeObservationEvent"] | components["schemas"]["WaterAccumulationEvent"] | components["schemas"]["RoadStatusEvent"] | components["schemas"]["BridgeStatusEvent"] | components["schemas"]["DrainageObstructionEvent"] | components["schemas"]["ConstructionActivityEvent"] | components["schemas"]["InfrastructureFailureEvent"] | components["schemas"]["RescueTeamStatusEvent"] | components["schemas"]["AmbulanceStatusEvent"] | components["schemas"]["HospitalCapacityEvent"] | components["schemas"]["ShelterCapacityEvent"] | components["schemas"]["ZoneStateEvent"] | components["schemas"]["ThreatDetectedEvent"] | components["schemas"]["ThreatEscalatedEvent"] | components["schemas"]["IncidentOpenedEvent"] | components["schemas"]["IncidentClosedEvent"] | components["schemas"]["AgentRunStartedEvent"] | components["schemas"]["AgentRunFinishedEvent"] | components["schemas"]["AgentNodeStartedEvent"] | components["schemas"]["AgentNodeFinishedEvent"] | components["schemas"]["ApprovalRequestedEvent"] | components["schemas"]["ApprovalDecidedEvent"] | components["schemas"]["ActionExecutedEvent"] | components["schemas"]["ActionVerifiedEvent"] | components["schemas"]["ReplanTriggeredEvent"] | components["schemas"]["AlertIssuedEvent"];
        /**
         * EventType
         * @enum {string}
         */
        EventType: "sim.tick" | "sim.status" | "sim.snapshot" | "sim.heartbeat" | "scenario.stage" | "weather.observation" | "weather.forecast" | "environment.soil" | "environment.river" | "environment.drainage" | "environment.slope" | "environment.water_accumulation" | "infrastructure.road" | "infrastructure.bridge" | "infrastructure.drainage_obstruction" | "infrastructure.construction" | "infrastructure.failure" | "emergency.rescue_team" | "emergency.ambulance" | "emergency.hospital" | "emergency.shelter";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** Heartbeat */
        Heartbeat: {
            /** Tick */
            tick: number;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
        };
        /** HeartbeatEvent */
        HeartbeatEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "sim.heartbeat";
            payload: components["schemas"]["Heartbeat"];
        };
        /** HospitalCapacity */
        HospitalCapacity: {
            /** Hospital Id */
            hospital_id: string;
            /**
             * Beds Total
             * @default 0
             */
            beds_total: number;
            /** Beds Occupied */
            beds_occupied: number;
            /**
             * Beds Available
             * @default 0
             */
            beds_available: number;
            /**
             * Er Status
             * @enum {string}
             */
            er_status: "normal" | "busy" | "overwhelmed";
        };
        /** HospitalCapacityEvent */
        HospitalCapacityEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "emergency.hospital";
            payload: components["schemas"]["HospitalCapacity"];
        };
        /** HospitalState */
        HospitalState: {
            /** Beds Occupied */
            beds_occupied: number;
            /**
             * Er Status
             * @default normal
             * @enum {string}
             */
            er_status: "normal" | "busy" | "overwhelmed";
        };
        /** InfrastructureFailure */
        InfrastructureFailure: {
            /** Asset Id */
            asset_id: string;
            /**
             * Asset Kind
             * @enum {string}
             */
            asset_kind: "slope" | "channel" | "bridge" | "road" | "power";
            /**
             * Failure Kind
             * @enum {string}
             */
            failure_kind: "landslide" | "culvert_collapse" | "embankment_breach" | "power_outage";
            /** Description */
            description: string;
        };
        /** InfrastructureFailureEvent */
        InfrastructureFailureEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "infrastructure.failure";
            payload: components["schemas"]["InfrastructureFailure"];
        };
        /** InjectRequest */
        InjectRequest: {
            event_type: components["schemas"]["EventType"];
            /** Location */
            location?: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Source
             * @default operator:api
             */
            source: string;
            severity?: components["schemas"]["Severity"] | null;
        };
        /** InjectionPreset */
        InjectionPreset: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            request: components["schemas"]["InjectRequest"];
        };
        /** MapBridge */
        MapBridge: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Road Id */
            road_id: string;
            /** Zone Id */
            zone_id: string;
            /** Crosses Id */
            crosses_id: string;
            xy: components["schemas"]["XY"];
        };
        /** MapChannel */
        MapChannel: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Zone Id */
            zone_id: string;
            /** Downstream Zone Id */
            downstream_zone_id: string;
            /** Design Capacity M3S */
            design_capacity_m3s: number;
            /** Current Capacity M3S */
            current_capacity_m3s: number;
            /** Svg Path */
            svg_path: string;
        };
        /** MapCrew */
        MapCrew: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Base Zone Id */
            base_zone_id: string;
            xy: components["schemas"]["XY"];
        };
        /** MapFeature */
        MapFeature: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "river" | "lake" | "hill_contour";
            /** Svg Path */
            svg_path: string;
            /** Label */
            label: string | null;
        };
        /** MapHospital */
        MapHospital: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Zone Id */
            zone_id: string;
            /** Beds Total */
            beds_total: number;
            xy: components["schemas"]["XY"];
        };
        /** MapProject */
        MapProject: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Zone Id */
            zone_id: string;
            /** Slope Id */
            slope_id: string | null;
            /** Planned Depth M */
            planned_depth_m: number;
            /** Permit Number */
            permit_number: string | null;
            /** Permit Doc Id */
            permit_doc_id: string | null;
            xy: components["schemas"]["XY"];
        };
        /** MapRoad */
        MapRoad: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Zone Ids */
            zone_ids: string[];
            /** Is Evacuation Route */
            is_evacuation_route: boolean;
            /** Is Only Access */
            is_only_access: boolean;
            /** Svg Path */
            svg_path: string;
        };
        /** MapSensor */
        MapSensor: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "rain_gauge" | "soil_moisture" | "channel_level" | "river_level" | "wind";
            /** Zone Id */
            zone_id: string | null;
            /** Target Id */
            target_id: string;
            xy: components["schemas"]["XY"];
        };
        /** MapShelter */
        MapShelter: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Zone Id */
            zone_id: string;
            /** Capacity */
            capacity: number;
            xy: components["schemas"]["XY"];
        };
        /** MapSlope */
        MapSlope: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Zone Id */
            zone_id: string;
            xy: components["schemas"]["XY"];
        };
        /** MapZone */
        MapZone: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Slope Deg */
            slope_deg: number;
            /** Soil Type */
            soil_type: string;
            /** Population */
            population: number;
            /** Drains To Channel Id */
            drains_to_channel_id: string | null;
            /** Svg Path */
            svg_path: string;
            label_xy: components["schemas"]["XY"];
        };
        /** ProjectState */
        ProjectState: {
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "halted";
            /**
             * Activity
             * @default idle
             * @enum {string}
             */
            activity: "excavating" | "idle" | "halted";
            /** Excavation Depth M */
            excavation_depth_m: number;
        };
        /** PumpDepot */
        PumpDepot: {
            /** Zone Id */
            zone_id: string;
            xy: components["schemas"]["XY"];
            /** Units */
            units: components["schemas"]["PumpUnit"][];
        };
        /** PumpUnit */
        PumpUnit: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Capacity M3S */
            capacity_m3s: number;
        };
        /** RescueTeamStatus */
        RescueTeamStatus: {
            /** Crew Id */
            crew_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "available" | "dispatched" | "en_route" | "on_site" | "blocked" | "busy" | "off_duty";
            /** Location Zone Id */
            location_zone_id: string;
            /**
             * Task
             * @default
             */
            task: string;
        };
        /** RescueTeamStatusEvent */
        RescueTeamStatusEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "emergency.rescue_team";
            payload: components["schemas"]["RescueTeamStatus"];
        };
        /** RiverObservation */
        RiverObservation: {
            /** Gauge Id */
            gauge_id: string;
            /** River Id */
            river_id: string;
            /** Level M */
            level_m: number;
            /** Flood Stage M */
            flood_stage_m: number;
            /** Warning Level M */
            warning_level_m: number;
            /** Danger Level M */
            danger_level_m: number;
            /**
             * Trend
             * @enum {string}
             */
            trend: "rising" | "steady" | "falling";
        };
        /** RiverObservationEvent */
        RiverObservationEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "environment.river";
            payload: components["schemas"]["RiverObservation"];
        };
        /** RiverState */
        RiverState: {
            /** Level M */
            level_m: number;
            /** Inflow M3S */
            inflow_m3s: number;
            /**
             * Trend
             * @default steady
             * @enum {string}
             */
            trend: "rising" | "steady" | "falling";
        };
        /** RoadState */
        RoadState: {
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "blocked" | "closed";
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** RoadStatus */
        RoadStatus: {
            /** Road Id */
            road_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "blocked" | "closed";
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Is Evacuation Route
             * @default false
             */
            is_evacuation_route: boolean;
        };
        /** RoadStatusEvent */
        RoadStatusEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "infrastructure.road";
            payload: components["schemas"]["RoadStatus"];
        };
        /** ScenarioInfo */
        ScenarioInfo: {
            name: components["schemas"]["ScenarioName"];
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Duration Ticks */
            duration_ticks: number;
            /** Stages */
            stages: components["schemas"]["StageInfo"][];
        };
        /**
         * ScenarioName
         * @enum {string}
         */
        ScenarioName: "normal_city" | "hillside_landslide" | "flash_flood" | "cascading_landslide_flood";
        /** ScenarioStage */
        ScenarioStage: {
            /** Scenario */
            scenario: string;
            /** Stage Index */
            stage_index: number;
            /** Stage */
            stage: string;
            /** Description */
            description: string;
            /** Tick */
            tick: number;
        };
        /** ScenarioStageEvent */
        ScenarioStageEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "scenario.stage";
            payload: components["schemas"]["ScenarioStage"];
        };
        /** SelectScenarioRequest */
        SelectScenarioRequest: {
            scenario: components["schemas"]["ScenarioName"];
            /** Seed */
            seed?: number | null;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "low" | "moderate" | "high" | "critical";
        /** ShelterCapacity */
        ShelterCapacity: {
            /** Shelter Id */
            shelter_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "closed" | "open" | "full";
            /**
             * Capacity
             * @default 0
             */
            capacity: number;
            /** Occupancy */
            occupancy: number;
        };
        /** ShelterCapacityEvent */
        ShelterCapacityEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "emergency.shelter";
            payload: components["schemas"]["ShelterCapacity"];
        };
        /** ShelterState */
        ShelterState: {
            /**
             * Status
             * @enum {string}
             */
            status: "closed" | "open" | "full";
            /** Occupancy */
            occupancy: number;
        };
        /** SimSnapshotEvent */
        SimSnapshotEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "sim.snapshot";
            payload: components["schemas"]["SimSnapshotPayload"];
        };
        /**
         * SimSnapshotPayload
         * @description Typed view of the ``sim.snapshot`` payload (``payloads.SimSnapshot`` keeps world and city as dicts).
         */
        SimSnapshotPayload: {
            status: components["schemas"]["SimStatus"];
            world: components["schemas"]["WorldSnapshot"];
            city: components["schemas"]["CityMap"];
        };
        /** SimStatus */
        SimStatus: {
            /**
             * State
             * @enum {string}
             */
            state: "idle" | "running" | "paused";
            /**
             * Running
             * @default false
             */
            running: boolean;
            /** Scenario */
            scenario: string;
            /** Seed */
            seed: number;
            /** Speed */
            speed: number;
            /** Tick */
            tick: number;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Stage */
            stage: string;
        };
        /** SimStatusEvent */
        SimStatusEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "sim.status";
            payload: components["schemas"]["SimStatus"];
        };
        /** SimTick */
        SimTick: {
            /** Tick */
            tick: number;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Scenario */
            scenario: string;
            /** Stage */
            stage: string;
            /** Speed */
            speed: number;
            /**
             * Running
             * @default false
             */
            running: boolean;
        };
        /** SimTickEvent */
        SimTickEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "sim.tick";
            payload: components["schemas"]["SimTick"];
        };
        /** SimulationSpeed */
        SimulationSpeed: {
            /** Speed */
            speed: number;
        };
        /** SimulationStart */
        SimulationStart: {
            scenario?: components["schemas"]["ScenarioName"] | null;
            /** Seed */
            seed?: number | null;
            /** Speed */
            speed?: number | null;
        };
        /** SimulationStatus */
        SimulationStatus: {
            /**
             * State
             * @enum {string}
             */
            state: "idle" | "running" | "paused";
            /** Running */
            running: boolean;
            scenario: components["schemas"]["ScenarioName"];
            /** Seed */
            seed: number;
            /** Speed */
            speed: number;
            /** Tick */
            tick: number;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            stage: components["schemas"]["StageInfo"] | null;
            /** Minutes Per Tick */
            minutes_per_tick: number;
            /** Tick Seconds */
            tick_seconds: number;
        };
        /** SlopeObservation */
        SlopeObservation: {
            /** Slope Id */
            slope_id: string;
            /** Movement Rate Mm H */
            movement_rate_mm_h: number;
            /** Cumulative Movement Mm */
            cumulative_movement_mm: number;
            /** Saturation */
            saturation: number;
        };
        /** SlopeObservationEvent */
        SlopeObservationEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "environment.slope";
            payload: components["schemas"]["SlopeObservation"];
        };
        /** SlopeState */
        SlopeState: {
            /** Saturation */
            saturation: number;
            /**
             * Movement Rate Mm H
             * @default 0
             */
            movement_rate_mm_h: number;
            /**
             * Cumulative Movement Mm
             * @default 0
             */
            cumulative_movement_mm: number;
        };
        /** SoilObservation */
        SoilObservation: {
            /** Probe Id */
            probe_id: string;
            /** Slope Id */
            slope_id: string | null;
            /** Soil Moisture Pct */
            soil_moisture_pct: number;
            /** Saturation */
            saturation: number;
        };
        /** SoilObservationEvent */
        SoilObservationEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "environment.soil";
            payload: components["schemas"]["SoilObservation"];
        };
        /** StageInfo */
        StageInfo: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Start Tick */
            start_tick: number;
        };
        /** StoredChunk */
        StoredChunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Document Title */
            document_title: string;
            /** Section Id */
            section_id: string;
            /** Section */
            section: string;
            /** Source */
            source: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "policy" | "sop" | "report" | "permit" | "change_log" | "profile";
            /**
             * Category
             * @enum {string}
             */
            category: "policy" | "sop" | "procedure" | "incident_report" | "infrastructure_report" | "engineering_report" | "construction_safety" | "evacuation" | "resource_rules" | "change_log";
            /** Zone Ids */
            zone_ids: string[];
            /** Hazards */
            hazards: ("flood" | "flash_flood" | "landslide" | "cyclone" | "urban_fire")[];
            /** Text */
            text: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ViewBox */
        ViewBox: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** WaterAccumulation */
        WaterAccumulation: {
            /** Zone Id */
            zone_id: string;
            /** Depth Cm */
            depth_cm: number;
            /**
             * Trend
             * @enum {string}
             */
            trend: "rising" | "steady" | "falling";
        };
        /** WaterAccumulationEvent */
        WaterAccumulationEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "environment.water_accumulation";
            payload: components["schemas"]["WaterAccumulation"];
        };
        /** WeatherForecast */
        WeatherForecast: {
            /**
             * Issued Sim Time
             * Format: date-time
             */
            issued_sim_time: string;
            /** Horizon H */
            horizon_h: number;
            /** Expected Total Mm */
            expected_total_mm: number;
            /** Peak Intensity Mm H */
            peak_intensity_mm_h: number;
            /** Confidence */
            confidence: number;
            /** Summary */
            summary: string;
        };
        /** WeatherForecastEvent */
        WeatherForecastEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "weather.forecast";
            payload: components["schemas"]["WeatherForecast"];
        };
        /**
         * WeatherObservation
         * @description A rain gauge reports rainfall, the wind station wind and temperature; unmeasured fields are None.
         */
        WeatherObservation: {
            /** Station Id */
            station_id: string;
            /** Rainfall Intensity Mm H */
            rainfall_intensity_mm_h: number | null;
            /** Cumulative Rainfall 24H Mm */
            cumulative_rainfall_24h_mm: number | null;
            /** Temperature C */
            temperature_c: number | null;
            /** Wind Speed Kmh */
            wind_speed_kmh: number | null;
            /** Wind Direction Deg */
            wind_direction_deg: number | null;
        };
        /** WeatherObservationEvent */
        WeatherObservationEvent: {
            /** Event Id */
            event_id: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Source */
            source: string;
            /** Location */
            location: string | null;
            severity: components["schemas"]["Severity"];
            /** Incident Id */
            incident_id: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "weather.observation";
            payload: components["schemas"]["WeatherObservation"];
        };
        /** WeatherState */
        WeatherState: {
            /** Temperature C */
            temperature_c: number;
            /** Wind Speed Kmh */
            wind_speed_kmh: number;
            /** Wind Direction Deg */
            wind_direction_deg: number;
        };
        /**
         * WorldSnapshot
         * @description Frozen, JSON-safe export of the whole world (``sim.snapshot`` and ``GET /api/simulation/snapshot``).
         */
        WorldSnapshot: {
            /** Tick */
            tick: number;
            /**
             * Sim Time
             * Format: date-time
             */
            sim_time: string;
            /** Stage Index */
            stage_index: number;
            weather: components["schemas"]["WeatherState"];
            forecast: components["schemas"]["WeatherForecast"] | null;
            /** Zones */
            zones: {
                [key: string]: components["schemas"]["ZoneConditions"];
            };
            /** Slopes */
            slopes: {
                [key: string]: components["schemas"]["SlopeState"];
            };
            /** Channels */
            channels: {
                [key: string]: components["schemas"]["ChannelState"];
            };
            /** Rivers */
            rivers: {
                [key: string]: components["schemas"]["RiverState"];
            };
            /** Roads */
            roads: {
                [key: string]: components["schemas"]["RoadState"];
            };
            /** Bridges */
            bridges: {
                [key: string]: components["schemas"]["BridgeState"];
            };
            /** Projects */
            projects: {
                [key: string]: components["schemas"]["ProjectState"];
            };
            /** Crews */
            crews: {
                [key: string]: components["schemas"]["CrewState"];
            };
            /** Ambulances */
            ambulances: {
                [key: string]: components["schemas"]["AmbulanceState"];
            };
            /** Hospitals */
            hospitals: {
                [key: string]: components["schemas"]["HospitalState"];
            };
            /** Shelters */
            shelters: {
                [key: string]: components["schemas"]["ShelterState"];
            };
        };
        /** XY */
        XY: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ZoneConditions */
        ZoneConditions: {
            /** Saturation */
            saturation: number;
            /**
             * Rainfall Intensity Mm H
             * @default 0
             */
            rainfall_intensity_mm_h: number;
            /**
             * Rain 24H Mm
             * @default 0
             */
            rain_24h_mm: number;
            /**
             * Water Depth Cm
             * @default 0
             */
            water_depth_cm: number;
            /**
             * Water Trend
             * @default steady
             * @enum {string}
             */
            water_trend: "rising" | "steady" | "falling";
        };
        LlmStatus: {
            /** @enum {string} */
            provider: "anthropic" | "mock" | "none";
            model: string | null;
        };
        /** @enum {string} */
        Band: "normal" | "watch" | "warning" | "critical";
        /** @enum {string} */
        Hazard: "landslide" | "flood";
        BandThresholds: {
            watch: number;
            warning: number;
            critical: number;
        };
        Bands: {
            landslide: components["schemas"]["BandThresholds"];
            flood: components["schemas"]["BandThresholds"];
        };
        ZoneState: {
            saturation: number;
            rain_24h_mm: number;
            rain_intensity_mm_h: number;
            landslide_index: number;
            flood_index: number;
            band: components["schemas"]["Band"];
            updated_sim_time: string;
        };
        ZoneStatePayload: components["schemas"]["ZoneState"] & {
            zone_id: string;
            prev_band?: components["schemas"]["Band"] | null;
        };
        ThreatPayload: {
            incident_id: string;
            zone_id: string;
            hazard: components["schemas"]["Hazard"];
            band: components["schemas"]["Band"];
            prev_band?: components["schemas"]["Band"] | null;
            index: number;
        };
        Citation: {
            id: string;
            /** @enum {string} */
            kind: "chunk" | "sensor" | "state" | "event";
            label: string;
        };
        Claim: {
            text: string;
            citation_ids: string[];
        };
        ContributingFactor: {
            factor: string;
            value: string;
            citation_ids: string[];
        };
        CitySnapshotReadings: {
            rain_intensity_mm_h: number;
            rain_24h_mm: number;
            saturation: number;
            landslide_index: number;
            flood_index: number;
            band: components["schemas"]["Band"];
        };
        SnapshotProject: {
            id: string;
            name: string;
            status: string;
            excavation_depth_m: number;
            planned_depth_m: number;
        };
        SnapshotChannel: {
            id: string;
            name: string;
            current_capacity_m3s: number;
            design_capacity_m3s: number;
            blocked_fraction: number;
        };
        SnapshotCrew: {
            id: string;
            name: string;
            status: string;
            location_zone_id: string;
        };
        CitySnapshot: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "observe";
            zone_id: string;
            sim_time: string;
            readings: components["schemas"]["CitySnapshotReadings"];
            project?: components["schemas"]["SnapshotProject"] | null;
            channel?: components["schemas"]["SnapshotChannel"] | null;
            crews: components["schemas"]["SnapshotCrew"][];
            open_roads: string[];
            closed_roads: string[];
            downstream_zone_ids: string[];
        };
        RetrievedChunk: {
            chunk_id: string;
            document_id: string;
            document_title: string;
            section_id: string;
            section: string;
            kind: string;
            similarity: number;
        };
        RetrievedChunks: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "retrieve";
            chunks: components["schemas"]["RetrievedChunk"][];
        };
        ThreatAssessment: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "assess";
            hazard: components["schemas"]["Hazard"];
            summary: string;
            contributing_factors: components["schemas"]["ContributingFactor"][];
            confidence: number;
            claims: components["schemas"]["Claim"][];
        };
        RiskPrediction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "predict";
            /** @enum {string} */
            probability_band: "low" | "moderate" | "high" | "very_high";
            time_horizon: string;
            onset_sim_time?: string | null;
            what_would_change_it: string[];
            claims: components["schemas"]["Claim"][];
        };
        CascadeLink: {
            cause: string;
            effect: string;
            affected_asset_ids: string[];
            citation_ids: string[];
        };
        CascadeAnalysis: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "cascade";
            chain: components["schemas"]["CascadeLink"][];
            affected_zone_ids: string[];
            claims: components["schemas"]["Claim"][];
        };
        ProposedAction: {
            action_id: string;
            tool: string;
            input: {
                [key: string]: unknown;
            };
            rationale: string;
            expected_effect: string;
            citation_ids: string[];
            requires_approval: boolean;
        };
        ActionPlan: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "recommend";
            actions: components["schemas"]["ProposedAction"][];
        };
        ApprovalGateResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "approval_gate";
            approval_id?: string | null;
            auto_approved_action_ids: string[];
            pending_action_ids: string[];
        };
        ExecuteResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "execute";
            action_ids: string[];
        };
        PerActionVerification: {
            action_id: string;
            /** @enum {string} */
            status: "verified" | "partially_verified" | "failed" | "pending";
            expected: string;
            observed: string;
            failures: string[];
        };
        VerificationResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "verify";
            /** @enum {string} */
            status: "verified" | "partially_verified" | "failed";
            per_action: components["schemas"]["PerActionVerification"][];
        };
        ReplanResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            node: "replan";
            reason: string;
        };
        StepOutput: components["schemas"]["CitySnapshot"] | components["schemas"]["RetrievedChunks"] | components["schemas"]["ThreatAssessment"] | components["schemas"]["RiskPrediction"] | components["schemas"]["CascadeAnalysis"] | components["schemas"]["ActionPlan"] | components["schemas"]["ApprovalGateResult"] | components["schemas"]["ExecuteResult"] | components["schemas"]["VerificationResult"] | components["schemas"]["ReplanResult"];
        /** @enum {string} */
        NodeName: "observe" | "retrieve" | "assess" | "predict" | "cascade" | "recommend" | "approval_gate" | "execute" | "verify" | "replan";
        AgentStep: {
            id: string;
            run_id: string;
            node: components["schemas"]["NodeName"];
            /** @enum {string} */
            status: "running" | "finished" | "ungrounded" | "failed";
            started_at: string;
            finished_at?: string | null;
            duration_ms?: number | null;
            output: components["schemas"]["StepOutput"] | null;
            citations: components["schemas"]["Citation"][];
        };
        AgentRun: {
            id: string;
            incident_id: string;
            thread_id: string;
            trigger: string;
            replan_reason?: string | null;
            /** @enum {string} */
            status: "running" | "waiting_approval" | "finished" | "failed";
            started_at: string;
            finished_at?: string | null;
            steps: components["schemas"]["AgentStep"][];
        };
        NodeStartedPayload: {
            run_id: string;
            incident_id: string;
            node: components["schemas"]["NodeName"];
            step_id: string;
        };
        ReplanPayload: {
            incident_id: string;
            run_id: string;
            reason: string;
        };
        /** @enum {string} */
        ApprovalStatus: "pending" | "approved" | "rejected" | "partial";
        Approval: {
            id: string;
            run_id: string;
            incident_id: string;
            proposed_actions: components["schemas"]["ProposedAction"][];
            status: components["schemas"]["ApprovalStatus"];
            requested_at: string;
            decided_at?: string | null;
            decided_by?: string | null;
            note?: string | null;
            approved_action_ids: string[];
            synthetic: boolean;
        };
        ApprovalDecision: {
            /** @enum {string} */
            decision: "approve" | "reject" | "partial";
            approved_action_ids: string[];
            note?: string | null;
        };
        StateChange: {
            /** @enum {string} */
            entity_type: "crew" | "shelter" | "road" | "bridge" | "project" | "channel" | "pump_unit" | "alert";
            entity_id: string;
            entity_name: string;
            field: string;
            from: string;
            to: string;
        };
        ActionVerification: {
            /** @enum {string} */
            status: "verified" | "partially_verified" | "failed" | "pending";
            expected: string;
            observed: string;
            failures: string[];
            checked_sim_time?: string | null;
        };
        /** @enum {string} */
        ActionStatus: "pending" | "executing" | "executed" | "failed";
        Action: {
            id: string;
            run_id: string;
            incident_id: string;
            tool: string;
            input: {
                [key: string]: unknown;
            };
            status: components["schemas"]["ActionStatus"];
            executed_at?: string | null;
            executed_sim_time?: string | null;
            state_changes: components["schemas"]["StateChange"][];
            verification?: components["schemas"]["ActionVerification"] | null;
        };
        ActionVerifiedPayload: {
            action_id: string;
            verification: components["schemas"]["ActionVerification"];
        };
        Alert: {
            id: string;
            zone_id: string;
            /** @enum {string} */
            level: "advisory" | "warning" | "evacuate";
            message: string;
            issued_at: string;
            issued_sim_time: string;
        };
        /** @enum {string} */
        IncidentStatus: "open" | "closed";
        IncidentSummary: {
            id: string;
            zone_id: string;
            hazard: components["schemas"]["Hazard"];
            band: components["schemas"]["Band"];
            status: components["schemas"]["IncidentStatus"];
            opened_at: string;
            opened_sim_time: string;
            closed_at?: string | null;
            run_count: number;
            pending_approval_count: number;
        };
        Incident: {
            id: string;
            zone_id: string;
            hazard: components["schemas"]["Hazard"];
            band: components["schemas"]["Band"];
            status: components["schemas"]["IncidentStatus"];
            opened_at: string;
            opened_sim_time: string;
            closed_at?: string | null;
            runs: components["schemas"]["AgentRun"][];
            approvals: components["schemas"]["Approval"][];
            actions: components["schemas"]["Action"][];
        };
        DocumentSection: {
            id: string;
            heading: string;
            text: string;
        };
        Document: {
            id: string;
            title: string;
            kind: string;
            sections: components["schemas"]["DocumentSection"][];
        };
        PendingEventEnvelope: {
            event_id: string;
            /** Format: date-time */
            timestamp: string;
            /** Format: date-time */
            sim_time: string;
            source: string;
            location: string | null;
            severity: components["schemas"]["Severity"];
            incident_id: string | null;
        };
        ZoneStateEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "zone.state";
            payload: components["schemas"]["ZoneStatePayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "zone.state";
        };
        ThreatDetectedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "threat.detected";
            payload: components["schemas"]["ThreatPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "threat.detected";
        };
        ThreatEscalatedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "threat.escalated";
            payload: components["schemas"]["ThreatPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "threat.escalated";
        };
        IncidentOpenedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "incident.opened";
            payload: components["schemas"]["Incident"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "incident.opened";
        };
        IncidentClosedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "incident.closed";
            payload: components["schemas"]["Incident"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "incident.closed";
        };
        AgentRunStartedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "agent.run.started";
            payload: components["schemas"]["AgentRun"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "agent.run.started";
        };
        AgentRunFinishedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "agent.run.finished";
            payload: components["schemas"]["AgentRun"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "agent.run.finished";
        };
        AgentNodeStartedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "agent.node.started";
            payload: components["schemas"]["NodeStartedPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "agent.node.started";
        };
        AgentNodeFinishedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "agent.node.finished";
            payload: components["schemas"]["AgentStep"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "agent.node.finished";
        };
        ApprovalRequestedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "approval.requested";
            payload: components["schemas"]["Approval"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "approval.requested";
        };
        ApprovalDecidedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "approval.decided";
            payload: components["schemas"]["Approval"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "approval.decided";
        };
        ActionExecutedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "action.executed";
            payload: components["schemas"]["Action"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "action.executed";
        };
        ActionVerifiedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "action.verified";
            payload: components["schemas"]["ActionVerifiedPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "action.verified";
        };
        ReplanTriggeredEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "replan.triggered";
            payload: components["schemas"]["ReplanPayload"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "replan.triggered";
        };
        AlertIssuedEvent: components["schemas"]["PendingEventEnvelope"] & {
            /** @constant */
            event_type: "alert.issued";
            payload: components["schemas"]["Alert"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event_type: "alert.issued";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_city_api_city_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityMap"];
                };
            };
        };
    };
    get_chunk_api_chunks__chunk_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredChunk"];
                };
            };
            /** @description Unknown chunk */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_status_api_simulation_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
        };
    };
    list_scenarios_api_simulation_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioInfo"][];
                };
            };
        };
    };
    get_snapshot_api_simulation_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSnapshot"];
                };
            };
        };
    };
    select_scenario_api_simulation_scenario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_simulation_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SimulationStart"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_api_simulation_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
        };
    };
    resume_api_simulation_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
        };
    };
    reset_api_simulation_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
        };
    };
    advance_api_simulation_advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AdvanceRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_speed_api_simulation_speed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationSpeed"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inject_api_simulation_inject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getLlmStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmStatus"];
                };
            };
        };
    };
    getDetectorBands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bands"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                since?: string;
                type?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    listIncidents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSummary"][];
                };
            };
        };
    };
    getIncident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Incident"];
                };
            };
        };
    };
    listApprovals: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApprovalStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"][];
                };
            };
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Approval"];
                };
            };
        };
    };
    listActions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Action"][];
                };
            };
        };
    };
    getAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Action"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
}
