// Generates src/api/schema.d.ts from the backend's contract plus the pending overlay.
//
//   openapi.json          written by backend/scripts/export_contract.py (`npm run gen:contract`); the source of truth
//   openapi.pending.yaml  hand-written contract for endpoints and events of later milestones (see its header)
//
// The overlay may only add: a path, schema or event type the backend already defines fails the merge, so each
// pending entry is deleted as soon as its backend lands. Pending events are appended to the backend's `Event` union.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString, COMMENT_HEADER } from 'openapi-typescript';
// openapi-typescript's own YAML loader (a dependency of openapi-typescript), so no extra package is needed.
import { parseYaml } from '@redocly/openapi-core';

const here = (p) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const backend = JSON.parse(readFileSync(here('openapi.json'), 'utf8'));
const pending = parseYaml(readFileSync(here('openapi.pending.yaml'), 'utf8'));

const problems = [];
const stale = (what) => problems.push(`${what} is now defined by the backend: delete it from openapi.pending.yaml`);

const merged = structuredClone(backend);
for (const [path, item] of Object.entries(pending.paths ?? {})) {
  if (path in merged.paths) stale(`path ${path}`);
  else merged.paths[path] = item;
}
const schemas = merged.components.schemas;
for (const [name, schema] of Object.entries(pending.components?.schemas ?? {})) {
  if (name in schemas) stale(`schema ${name}`);
  else schemas[name] = schema;
}

const union = schemas.Event;
if (!union?.oneOf || !union.discriminator?.mapping) throw new Error('backend openapi.json has no discriminated Event union');
const eventTypeOf = (schema) =>
  [schema, ...(schema.allOf ?? [])].map((part) => part.properties?.event_type?.const).find((c) => typeof c === 'string');
for (const name of pending['x-pending-events'] ?? []) {
  const eventType = eventTypeOf(pending.components.schemas[name] ?? {});
  if (!eventType) throw new Error(`pending event ${name} has no event_type const`);
  if (eventType in union.discriminator.mapping) {
    stale(`event type ${eventType} (${name})`);
    continue;
  }
  union.oneOf.push({ $ref: `#/components/schemas/${name}` });
  union.discriminator.mapping[eventType] = `#/components/schemas/${name}`;
}

if (problems.length > 0) {
  console.error(problems.map((p) => `gen:api: ${p}`).join('\n'));
  process.exit(1);
}

const banner =
  '// GENERATED by scripts/gen-api.mjs from openapi.json (backend) + openapi.pending.yaml (pending overlay).\n' +
  '// Do not edit. Run `npm run gen:api` after a backend contract change.\n';
const ast = await openapiTS(merged);
writeFileSync(here('src/api/schema.d.ts'), `${COMMENT_HEADER}${banner}\n${astToString(ast)}`);
console.log('wrote src/api/schema.d.ts');
