"""Reference tables for the dataset checks: which field points at which table (spec §5).

Polymorphic references (``asset_kind`` + ``asset_id``) resolve through ``ASSET_KINDS``.
"""

from collections.abc import Mapping
from types import MappingProxyType

# (table, field, referenced table). List-valued fields are checked item by item.
REFERENCES: tuple[tuple[str, str, str], ...] = (
    ("zones", "geological_zone_id", "geological_zones"),
    ("zones", "catchment_id", "catchments"),
    ("zones", "drains_to_channel_id", "drainage_channels"),
    ("soil_profiles", "zone_id", "zones"),
    ("catchments", "zone_ids", "zones"),
    ("catchments", "outlet_river_id", "rivers"),
    ("rivers", "gauge_sensor_id", "sensors"),
    ("hills", "zone_ids", "zones"),
    ("hills", "geological_zone_id", "geological_zones"),
    ("slopes", "zone_id", "zones"),
    ("slopes", "hill_id", "hills"),
    ("slopes", "toe_channel_id", "drainage_channels"),
    ("flood_plains", "river_id", "rivers"),
    ("flood_plains", "zone_ids", "zones"),
    ("drainage_channels", "catchment_id", "catchments"),
    ("drainage_channels", "upstream_zone_id", "zones"),
    ("drainage_channels", "downstream_zone_id", "zones"),
    ("drainage_channels", "outfall_river_id", "rivers"),
    ("drainage_channels", "outfall_channel_id", "drainage_channels"),
    ("pump_units", "location_zone_id", "zones"),
    ("pump_units", "channel_id", "drainage_channels"),
    ("roads", "zone_id", "zones"),
    ("roads", "from_zone_id", "zones"),
    ("roads", "to_zone_id", "zones"),
    ("bridges", "road_id", "roads"),
    ("bridges", "zone_id", "zones"),
    ("tunnels", "road_id", "roads"),
    ("tunnels", "zone_id", "zones"),
    ("tunnels", "sump_pump_ids", "pump_units"),
    ("dams", "river_id", "rivers"),
    ("dams", "channel_id", "drainage_channels"),
    ("dams", "zone_id", "zones"),
    ("dams", "downstream_zone_ids", "zones"),
    ("power_substations", "zone_id", "zones"),
    ("power_substations", "serves_zone_ids", "zones"),
    ("power_substations", "fed_from_substation_id", "power_substations"),
    ("water_facilities", "zone_id", "zones"),
    ("water_facilities", "serves_zone_ids", "zones"),
    ("water_facilities", "substation_id", "power_substations"),
    ("projects", "zone_id", "zones"),
    ("projects", "slope_id", "slopes"),
    ("projects", "permit_doc_id", "documents"),
    ("projects", "flood_plain_id", "flood_plains"),
    ("projects", "nearest_channel_id", "drainage_channels"),
    ("critical_infrastructure", "zone_id", "zones"),
    ("critical_infrastructure", "depends_on_substation_id", "power_substations"),
    ("critical_infrastructure", "depends_on_water_facility_id", "water_facilities"),
    ("critical_infrastructure", "access_road_id", "roads"),
    ("sensors", "zone_id", "zones"),
    ("sensors", "channel_id", "drainage_channels"),
    ("sensors", "slope_id", "slopes"),
    ("sensors", "river_id", "rivers"),
    ("hospitals", "zone_id", "zones"),
    ("hospitals", "access_road_id", "roads"),
    ("hospitals", "substation_id", "power_substations"),
    ("hospitals", "water_facility_id", "water_facilities"),
    ("hospital_beds", "hospital_id", "hospitals"),
    ("ambulances", "hospital_id", "hospitals"),
    ("ambulances", "location_zone_id", "zones"),
    ("fire_stations", "zone_id", "zones"),
    ("fire_stations", "coverage_zone_ids", "zones"),
    ("fire_stations", "access_road_id", "roads"),
    ("fire_trucks", "station_id", "fire_stations"),
    ("fire_trucks", "location_zone_id", "zones"),
    ("police_stations", "zone_id", "zones"),
    ("police_stations", "jurisdiction_zone_ids", "zones"),
    ("crews", "base_zone_id", "zones"),
    ("crews", "location_zone_id", "zones"),
    ("shelters", "zone_id", "zones"),
    ("shelters", "flood_plain_id", "flood_plains"),
    ("shelters", "school_id", "schools"),
    ("shelters", "access_road_id", "roads"),
    ("zone_yearly_stats", "zone_id", "zones"),
    ("residential_areas", "zone_id", "zones"),
    ("residential_areas", "slope_id", "slopes"),
    ("residential_areas", "flood_plain_id", "flood_plains"),
    ("residential_areas", "nearest_channel_id", "drainage_channels"),
    ("schools", "zone_id", "zones"),
    ("schools", "shelter_id", "shelters"),
    ("schools", "flood_plain_id", "flood_plains"),
    ("schools", "slope_id", "slopes"),
    ("infrastructure_changes", "zone_id", "zones"),
    ("infrastructure_changes", "project_id", "projects"),
    ("infrastructure_changes", "document_id", "documents"),
    ("infrastructure_changes", "related_incident_id", "historical_incidents"),
    ("policy_thresholds", "document_id", "documents"),
)

# Polymorphic ``asset_kind`` values -> table.
ASSET_KINDS: Mapping[str, str] = MappingProxyType(
    {
        "zone": "zones",
        "river": "rivers",
        "slope": "slopes",
        "flood_plain": "flood_plains",
        "drainage_channel": "drainage_channels",
        "pump_unit": "pump_units",
        "road": "roads",
        "bridge": "bridges",
        "tunnel": "tunnels",
        "dam": "dams",
        "power_substation": "power_substations",
        "water_facility": "water_facilities",
        "project": "projects",
        "sensor": "sensors",
        "hospital": "hospitals",
        "fire_station": "fire_stations",
        "fire_truck": "fire_trucks",
        "police_station": "police_stations",
        "crew": "crews",
        "shelter": "shelters",
        "residential_area": "residential_areas",
        "school": "schools",
    }
)
CROSSES_KINDS: Mapping[str, str] = MappingProxyType({"river": "rivers", "channel": "drainage_channels"})

# (table, zone field) for located records whose (x_m, y_m) must lie inside that zone's bbox. Roads are exempt.
IN_ZONE: tuple[tuple[str, str], ...] = (
    ("slopes", "zone_id"),
    ("drainage_channels", "upstream_zone_id"),
    ("pump_units", "location_zone_id"),
    ("bridges", "zone_id"),
    ("tunnels", "zone_id"),
    ("dams", "zone_id"),
    ("power_substations", "zone_id"),
    ("water_facilities", "zone_id"),
    ("projects", "zone_id"),
    ("sensors", "zone_id"),
    ("hospitals", "zone_id"),
    ("fire_stations", "zone_id"),
    ("police_stations", "zone_id"),
    ("crews", "location_zone_id"),
    ("shelters", "zone_id"),
    ("residential_areas", "zone_id"),
    ("schools", "zone_id"),
)
